### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'exportxml'

### ISSUE THREAD

**Issue by Fran89** [crotwell/2extStationXML#3]
No idea why when running this some objects are not returned as such, but as dictionaries. I put in some debug code on line 395:

`v.exportxml(outfile, nsk, sublevel, ignorewarning)`

and I put in a try-except block with prints to see what 'v' and 'k' were. It turns out 'v' in this instance is just a python dictionary with : 

`{'ValueOf": number}`

while k is any single value (latitude, longitude, dip, etc) for the channel. Also from the channel 

`{'Name' : ----, 'Description' : ----} `

are also spat out as dictionaries. Everything else builds fine. I tried casting, building nodes, etc, but I cannot get this to work, any idea what I'm missing?

Thanks,
Fran89

**Comment by crotwell** [comment]
I think this happens in the SIS stationxml parser. I thought Prabha has fixed this issue, but perhaps not. Just to be sure, have you pulled the latest from Github?

Can you give some more info on how to reproduce this?

thanks
Philip

**Comment by crotwell** [comment]
Closing this, please reopen if you can give me information on how to reproduce. Otherwise I'll assume it is ok. Thanks.
